export const STARTLOADER = "STARTLOADER";
export const STOPLOADER = "STOPLOADER";
export const SETMSG = "SETMSG";
export const CLRMSG = "CLRMSG";
export const FETCHHEADS = "FETCHHEADS";

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_FIRST_NAME = "SET_USER_FIRST_NAME";
export const GET_SUCCESS_MSG = "GET_SUCCESS_MSG";
export const RESET_ALL_STATE = "RESET_ALL_STATE";
export const RESET_SUCCESS_STATE = "RESET_SUCCESS_STATE";
export const RESET_ERROR_STATE = "RESET_ERROR_STATE";

export const NEWSFEED = 'NEWSFEED';
export const SET_TWEET_VIEW_DATA =  'SET_TWEET_VIEW_DATA';
export const FOLLOWING = 'FOLLOWING';
export const POST_TWEET = 'POST_TWEET';
export const SET_BOOKMARKS = 'SET_BOOKMARKS';

export const GET_RECOMMENDATION = 'GET_RECOMMENDATION';
export const HANDLE_SEARCH = 'HANDLE_SEARCH';
export const NEWSFEED_HASHTAG = 'NEWSFEED_HASHTAG';

export const GETUSERPROFILE = 'GETUSERPROFILE'
